### ISSUE TITLE
Gen-basis compilation error in siesta 4.1.5

### ISSUE THREAD

**Issue by AleksBL** [siesta-project/buds#9]
Sorry for the inconvenience, but when i try to compile the "Gen-basis" utility, i get the following error:

Fatal Error: Cannot open module file ‘version_info.mod’ for reading at (1): No such file or directory

Siesta is installed and can run, together with  a couple of other utilities in the "Util" directory.

BR Aleksander

**Comment by albgar** [comment]
(A preliminary comment: you should create issues for Siesta in https://gitlab.com/siesta-project/siesta, not in this GitHub repo, which deals with something else)

There is indeed a problem in the compilation of gen-basis in Siesta-4.1.5. You can apply a fix by dowloading  [this patch file](https://github.com/siesta-project/buds/files/7114452/gen-basis-patch.txt ), going to the top Siesta distribution directory and typing

```
  patch -p1 < /path/to/gen-basis-patch.txt
```
Recompile Siesta and then recompile Gen-basis.
